# Stage 1: Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package management files
COPY package.json package-lock.json ./

# Install all dependencies including devDependencies (needed for build)
RUN npm ci

# Copy the rest of the frontend files
COPY . .

# Build the Nuxt application
RUN npm run build

# Stage 2: Production runner stage
FROM node:20-alpine AS runner

WORKDIR /app

# Copy the build output from the builder stage
COPY --from=builder /app/.output ./.output

EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=production

# Run the standalone Node.js server generated by Nitro
CMD ["node", ".output/server/index.mjs"]
